// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FavoriteSearchController from "./favorite_search_controller"
application.register("favorite-search", FavoriteSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndexSearchController from "./index_search_controller"
application.register("index-search", IndexSearchController)

import MapShowController from "./map_show_controller"
application.register("map-show", MapShowController)
